version: 0.2

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "nothing to do in pre_build"

  build:
    commands:
      - echo "Copying assets to output buckets `date` in `pwd`"
      - echo "Copying S3 assets to /$VERSION/"
      - aws s3 cp deployment/dist/ s3://$BUILD_OUTPUT_BUCKET/live-streaming-with-automated-multi-language-subtitling/$VERSION/ --recursive --acl bucket-owner-full-control
      - aws s3 cp deployment/dist/live-streaming-with-automated-multi-language-subtitling.template s3://$TEMPLATE_OUTPUT_BUCKET/live-streaming-with-automated-multi-language-subtitling/$VERSION/ --acl bucket-owner-full-control
      - echo "Copying assets to output bucket complete `date`"
      - echo "Copying new buildspec `date` in `pwd`"
      - mv deployment/buildspecs/$PIPELINE_TYPE-github-spec.yml buildspec.yml
      - echo "Copying new buildspec complete `date`"

artifacts:
  files:
      - deployment/buildspecs/*
      - deployment/open-source/*
      - buildspec.yml
  post_build:
    commands:
      - echo "deployment of assets to S3 completed on `date`"
